name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for client
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run Prettier for client
        run: |
          cd client
          npx prettier --check .

      - name: Run ESLint for client
        run: |
          cd client
          npx eslint .

      - name: Run Tests for client
        run: |
          cd client
          npm test -- --watchAll=false --ci

      - name: Build client
        run: |
          cd client
          npm run build

  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run ESLint for server
        run: |
          cd server
          npx eslint .

      - name: Run Tests for server
        run: |
          cd server
          npm test -- --watchAll=false --ci

      - name: Build server
        run: |
          cd server
          npm run start
